insert into COUNTRY(COUNTRY_ID, NAME, STATUS, DESCRIPTION) VALUES ('2', 'РФ', 'Active', '');
insert into REGION(REGION_ID, NAME, STATUS, COUNTRY_ID, DESCRIPTION) VALUES ('3', 'РО', 'Active', '2', '');
insert into TOWN(TOWN_ID, NAME, STATUS, REGION_ID, DESCRIPTION) VALUES ('45', 'Ростов', 'Active', '3', '');
insert into LOCATION(LOCATION_ID, COUNTRY_ID, REGION_ID, TOWN_ID) VALUES ('4', '2', '3', '45');

insert into ORGANIZATION(ORGANIZATION_ID, NAME, STATUS, LOCATION_ID, DESCRIPTION) VALUES ('1001', 'Школа №1001', 'Active', '4', '');
insert into ORGANIZATION(ORGANIZATION_ID, NAME, STATUS, LOCATION_ID, DESCRIPTION) VALUES ('1002', 'Школа №1002', 'Active', '4', '');
insert into ORGANIZATION(ORGANIZATION_ID, NAME, STATUS, LOCATION_ID, DESCRIPTION) VALUES ('1003', 'Школа №1003', 'Active', '4', '');
insert into ORGANIZATION(ORGANIZATION_ID, NAME, STATUS, LOCATION_ID, DESCRIPTION) VALUES ('1004', 'Школа №1004', 'Active', '4', '');
