CREATE TABLE COUNTRY (
  COUNTRY_ID varchar(32) NOT NULL,
  NAME varchar(255) NOT NULL,
  DESCRIPTION varchar(255),
  STATUS varchar(32),
  PRIMARY KEY (COUNTRY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;