CREATE TABLE REGION (
  REGION_ID varchar(32) NOT NULL,
  NAME varchar(255) NOT NULL,
  DESCRIPTION varchar(512),
  STATUS varchar(32) NOT NULL,
  COUNTRY_ID varchar(32) NOT NULL,
  PRIMARY KEY (REGION_ID),
  FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY(COUNTRY_ID) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

