  CREATE TABLE TOWN (
    TOWN_ID varchar(32) NOT NULL,
    NAME varchar(255) NOT NULL,
    DESCRIPTION varchar(255),
    STATUS varchar(32) NOT NULL,
    REGION_ID varchar(32) NOT NULL,
    DISTRICT_ID varchar(32),
    PRIMARY KEY (TOWN_ID),
    FOREIGN KEY (REGION_ID) REFERENCES REGION(REGION_ID),
    FOREIGN KEY (DISTRICT_ID) REFERENCES DISTRICT(DISTRICT_ID)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8;