CREATE TABLE LOCATION (
  LOCATION_ID varchar(32) NOT NULL,
  COUNTRY_ID varchar(32) NOT NULL,
  REGION_ID varchar(32) NOT NULL,
  DISTRICT_ID varchar(32),
  TOWN_ID varchar(32),
  TOWN_AREA_ID varchar(32),
  PRIMARY KEY (LOCATION_ID),
  FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY(COUNTRY_ID),
  FOREIGN KEY (REGION_ID) REFERENCES REGION(REGION_ID),
  FOREIGN KEY (DISTRICT_ID) REFERENCES DISTRICT(DISTRICT_ID),
  FOREIGN KEY (TOWN_ID) REFERENCES TOWN(TOWN_ID),
  FOREIGN KEY (TOWN_AREA_ID) REFERENCES TOWN_AREA(TOWN_AREA_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;