CREATE TABLE ORGANIZATION (
  ORGANIZATION_ID varchar(32) NOT NULL,
  NAME varchar(255) NOT NULL,
  DESCRIPTION varchar(255),
  STATUS varchar(32) NOT NULL,
  PHONE varchar(64),
  ADDRESS varchar(255),
  LOCATION_ID varchar(32) NOT NULL,
  PRIMARY KEY (ORGANIZATION_ID),
  FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION(LOCATION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;