CREATE TABLE GROUPS (
  GROUP_ID varchar(32) NOT NULL,
  ORGANIZATION_ID varchar(32) NOT NULL,
  NAME varchar(255) NOT NULL,
  NUMBER varchar(255),
  STATUS varchar(32) NOT NULL,
  DESCRIPTION varchar (255),
  LAST_UPDATE_TIME DATETIME,
  UPDATE_BY_USER_ID varchar(32),
  CREATE_TIME DATETIME,
  CREATE_BY_USER_ID varchar(32),
  PRIMARY KEY (GROUP_ID),
  FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION(ORGANIZATION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;