CREATE TABLE USER_PARENT (
  PARENT_USER_ID varchar(32) NOT NULL,
  USER_ID varchar(32) NOT NULL,
  PARENT_TYPE varchar(32),
  FOREIGN KEY (PARENT_USER_ID) REFERENCES USERS(USER_ID),
  FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
