CREATE TABLE NOTIFICATION (
  NOTIFICATION_ID varchar(32) NOT NULL,
  NAME varchar(255) NOT NULL,
  DESCRIPTION varchar(255),
  TEXT MEDIUMTEXT,
  DATE_ON DATETIME,
  TYPE_NOTIFICATION varchar(32),
  STATUS varchar(32),
  USER_TYPE varchar(32),
  SETTING_MAIL_ID varchar(32),
  USER_ID varchar(32),
  GROUP_ID varchar(32),
  ORGANIZATION_ID varchar(32),
  CREATE_BY_USER_ID varchar(32),
  CREATE_TIME DATETIME,
  UPDATE_BY_USER_ID varchar(32),
  LAST_UPDATE_TIME DATETIME,
  PRIMARY KEY (NOTIFICATION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;