CREATE TABLE SETTINGS_MAIL (
  SETTINGS_MAIL_ID varchar(32) NOT NULL,
  NAME varchar(255) NOT NULL,
  DESCRIPTION varchar(512),
  STATUS varchar(32),
  HOST varchar(32),
  PORT varchar(32),
  USER_NAME varchar(32),
  USER_PASSWORD varchar(32),
  DEFAULT_SENDER varchar(128),
  DEFAULT_SUBJECT_PREFIX varchar(128),
  ORGANIZATION_ID varchar(32),
  PRIMARY KEY (SETTINGS_MAIL_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;