CREATE TABLE BILL_USER (
  BILL_USER_ID varchar(32) NOT NULL,
  NAME varchar(255) NOT NULL,
  DESCRIPTION varchar(255),
  STATUS varchar(32) NOT NULL,
  STATUS_BILL varchar(32) NOT NULL,
  USER_PHONE varchar(32) NOT NULL,
  AMOUNT DOUBLE NOT NULL,
  CCY varchar(32) NOT NULL,
  COMMENT varchar(32),
  LIFETIME DATETIME,
  PAY_SOURCE varchar(32),
  PRV_NAME varchar(32),
  PRV_ID varchar(32),
  USER_ID varchar(32),
  PRIMARY KEY (BILL_USER_ID),
  FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;