//выполнять по одному скрипту

  ALTER TABLE USER RENAME USERS;



ALTER TABLE my3o.ORGANIZATION_USER DROP FOREIGN KEY ORGANIZATION_USER_ibfk_2;

ALTER TABLE my3o.ORGANIZATION_USER
ADD FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID);



ALTER TABLE my3o.GROUP_USER DROP FOREIGN KEY GROUP_USER_ibfk_2;

ALTER TABLE my3o.GROUP_USER
ADD FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID);



ALTER TABLE my3o.USER_PARENT DROP FOREIGN KEY USER_PARENT_ibfk_1;

ALTER TABLE my3o.USER_PARENT DROP FOREIGN KEY USER_PARENT_ibfk_2;

ALTER TABLE my3o.USER_PARENT
ADD FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID);

ALTER TABLE my3o.USER_PARENT
ADD FOREIGN KEY (PARENT_USER_ID) REFERENCES USERS(USER_ID);



ALTER TABLE my3o.BILL_USER DROP FOREIGN KEY BILL_USER_ibfk_1;

ALTER TABLE my3o.BILL_USER
ADD FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID);