CREATE TABLE JOURNAL (
  JOURNAL_ID varchar(32) NOT NULL,
  SHEDULE_ID varchar(32) NOT NULL,
  DATE varchar(16) NOT NULL,
  USER_ID varchar(32) NOT NULL,
  MARK varchar(32) NOT NULL,
  MARK_TYPE varchar(32) NOT NULL,
  TASK_TYPE varchar(32) NOT NULL,
  DESCRIPTION varchar(255),
  STATUS varchar(32) NOT NULL,
  PRIMARY KEY (JOURNAL_ID),
  FOREIGN KEY (SHEDULE_ID) REFERENCES SHEDULES(SHEDULE_ID),
  FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;